# -*- coding: utf-8 -*-
"""finetuningfiqa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ2pDjEyuOy6EhpFZTD2zuo_a5lftlUf
"""

!pip install datasets==3.6.0

# os.environ["HUGGINGFACEHUB_API_TOKEN"] = ""
import os
from getpass import getpass
HF_token = getpass()
os.environ['HUGGINGFACEHUB_API_TOKEN'] = HF_token

import datasets
from datasets import load_dataset
print(datasets.__version__)

dataset = load_dataset("BeIR/fiqa", name="corpus", split="corpus")

corpus

queries_dataset = load_dataset("BeIR/fiqa", "queries", split="queries")

queries_dataset

print(f"   Documents: {len(dataset)}")
print(f"   Queries: {len(queries_dataset)}")

documents = []
for item in dataset:
    doc_text = item['text']
    documents.append(doc_text)

queries = []
for item in queries_dataset:
    query_text = item['text']
    queries.append(query_text)

print(f"✅ Prepared {len(documents)} documents and {len(queries)} queries")

print(f"   Sample query: {queries[0][:100]}...")
print(f"   Sample document: {documents[0][:100]}...")

"""Creating training pairs..."""

import random
training_pairs = []
labels = []

# Create 5,000 positive pairs (query with a relevant document)
print("   Creating positive pairs...")
for i in range(5000):
    query_idx = random.randint(0, len(queries) - 1)
    doc_idx = random.randint(0, len(documents) - 1)

    training_pairs.append({
        'query': queries[query_idx],
        'document': documents[doc_idx]
    })
    labels.append(1)

# Create 5,000 negative pairs (query with a random unrelated document)
print("   Creating negative pairs...")
for i in range(5000):
    query_idx = random.randint(0, len(queries) - 1)
    doc_idx = random.randint(0, len(documents) - 1)

    training_pairs.append({
        'query': queries[query_idx],
        'document': documents[doc_idx]
    })
    labels.append(0)

print(f"✅ Created {len(training_pairs)} training pairs")
print(f"   Positive pairs: {labels.count(1)}")
print(f"   Negative pairs: {labels.count(0)}")

"""Split Data into Training and Validation Sets"""

from sklearn.model_selection import train_test_split
train_pairs, val_pairs, train_labels, val_labels = train_test_split(
    training_pairs, labels, test_size=0.2, random_state=42
)

print(f"✅ Data split complete!")
print(f"   Training samples: {len(train_pairs)}")
print(f"   Validation samples: {len(val_pairs)}")

"""Load Tokenizer and Model"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

print(" Model and tokenizer loaded successfully!")
print(f"   Model: {model_name}")

import torch

train_encodings = tokenizer(
    [pair['query'] for pair in train_pairs],
    [pair['document'] for pair in train_pairs],
    truncation=True,
    padding=True,
    max_length=512
)

val_encodings = tokenizer(
    [pair['query'] for pair in val_pairs],
    [pair['document'] for pair in val_pairs],
    truncation=True,
    padding=True,
    max_length=512
)

import torch

class RelevanceDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset = RelevanceDataset(train_encodings, train_labels)
val_dataset = RelevanceDataset(val_encodings, val_labels)

print(f"   Training dataset size: {len(train_dataset)}")
print(f"   Validation dataset size: {len(val_dataset)}")

!pip install --upgrade transformers

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./financial_reranker',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to=[]
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

trainer.train()

model.save_pretrained('./financial_reranker_model')
tokenizer.save_pretrained('./financial_reranker_model')

# Load the saved model
test_model = AutoModelForSequenceClassification.from_pretrained('./financial_reranker_model')
test_tokenizer = AutoTokenizer.from_pretrained('./financial_reranker_model')

test_query = "What are the best investment strategies for retirement?"
test_doc_relevant = "Retirement investment strategies include diversifying your portfolio with stocks, bonds, and mutual funds."
test_doc_irrelevant = "The weather today is sunny with a high of 75 degrees."

# Predict relevance for irrelevant document
inputs_irrelevant = test_tokenizer(test_query, test_doc_irrelevant, return_tensors="pt", truncation=True, padding=True)
outputs_irrelevant = test_model(**inputs_irrelevant)
prediction_irrelevant = torch.softmax(outputs_irrelevant.logits, dim=1)

print(f"\nQuery: {test_query}")
print(f"\n📄 Relevant Document: {test_doc_relevant}")
print(f"   Relevance Score: {prediction_relevant[0][1].item():.4f}")
print(f"\n📄 Irrelevant Document: {test_doc_irrelevant}")
print(f"   Relevance Score: {prediction_irrelevant[0][1].item():.4f}")