# -*- coding: utf-8 -*-
"""finetuningfiqa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ2pDjEyuOy6EhpFZTD2zuo_a5lftlUf
"""

#pip install datasets==3.6.0

# os.environ["HUGGINGFACEHUB_API_TOKEN"] = ""
import os
from getpass import getpass
HF_token = getpass()
os.environ['HUGGINGFACEHUB_API_TOKEN'] = HF_token

!pip install beir

from beir import util, LoggingHandler
from beir.datasets.data_loader import GenericDataLoader
import logging
import pathlib

# Setup logging
logging.basicConfig(format='%(asctime)s - %(message)s',
                    level=logging.INFO,
                    handlers=[LoggingHandler()])


url = f"https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip"
data_path = util.download_and_unzip(url, "datasets")

corpus, queries, qrels = GenericDataLoader(data_folder=data_path).load(split="train")

print(f"Corpus size: {len(corpus)}")
print(f"Queries size: {len(queries)}")
print(f"Qrels size: {len(qrels)}")

corpus_first_key = next(iter(corpus)) # Get the first key from corpus
print(f"Corpus entry for key '{corpus_first_key}': {corpus[corpus_first_key]}")
print(f"Queries entry for key '0': {queries['0']}")
print(f"Qrels entry for key '0': {qrels['0']}")

import datasets
from datasets import load_dataset
print(datasets.__version__)

dataset = load_dataset("BeIR/fiqa", name="corpus", split="corpus")

"""https://ir-datasets.com/beir#beir/fiqa/train"""

from huggingface_hub import list_datasets
datasets_list = list_datasets()
print("fiqa" in datasets_list)

dataset

dataset[0]

queries_dataset = load_dataset("BeIR/fiqa", "queries", split="queries")

queries_dataset



print(f"id: {queries_dataset[0]['_id']}")
print(f"title: {queries_dataset[0]['title']}")
print(f"text: {queries_dataset[0]['text']}")

print(f" Documents: {len(dataset)}")
print(f"Queries: {len(queries_dataset)}")

documents = []
for item in dataset:
    doc_text = item['text']
    documents.append(doc_text)

queries = []
for item in queries_dataset:
    query_text = item['text']
    queries.append(query_text)

print(f"{len(documents)} documents and {len(queries)} queries")

qrels = load_dataset("BeIR/fiqa", name="qrels")

print(f"query: {queries[1][:200]}...")
print(f"document: {documents[1][:200]}...")



"""Split Data into Training and Validation Sets"""

from sklearn.model_selection import train_test_split
train_pairs, val_pairs, train_labels, val_labels = train_test_split(
    training_pairs, labels, test_size=0.2, random_state=42
)

print(f" data split complete!")
print(f"training samples: {len(train_pairs)}")
print(f"validation samples: {len(val_pairs)}")

"""Load Tokenizer and Model

https://stackoverflow.com/questions/75172073/how-to-use-automodelforsequenceclassification-for-multiclass-classification
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

print(" model and tokenizer loaded successfully!")
print(f"   model: {model_name}")

"""###https://huggingface.co/transformers/v4.7.0/preprocessing.html"""

import torch

train_encodings = tokenizer(
    [pair['query'] for pair in train_pairs],
    [pair['document'] for pair in train_pairs],
    truncation=True,
    padding=True,
    max_length=512
)

train_encodings.keys()

val_encodings = tokenizer(
    [pair['query'] for pair in val_pairs],
    [pair['document'] for pair in val_pairs],
    truncation=True,
    padding=True,
    max_length=512
)

"""###https://torchtext.readthedocs.io/en/latest/data.html
###https://www.geeksforgeeks.org/deep-learning/how-do-you-use-pytorchs-dataset-and-dataloader-classes-for-custom-data/
###https://towardsdatascience.com/how-to-use-datasets-and-dataloader-in-pytorch-for-custom-text-data-270eed7f7c00/
"""

import torch

class RelevanceDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset = RelevanceDataset(train_encodings, train_labels)
val_dataset = RelevanceDataset(val_encodings, val_labels)

print(f"Training dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(val_dataset)}")

!pip install --upgrade transformers

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./financial_reranker',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to=[]
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

trainer.train()

model.save_pretrained('./financial_reranker_model')
tokenizer.save_pretrained('./financial_reranker_model')

